# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-31 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('createtime', models.DateTimeField()),
                ('num', models.IntegerField()),
                ('isGood', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField()),
                ('banNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Banji')),
            ],
        ),
    ]
